import { navroutes } from "./navroutes";

export const DEFAULT_PAGE_SIZE = 10;

export const sidebarItems = [
  {
    icon: "home",
    label: "Dashboard",
    href: navroutes.DASHBOARD,
    title: "Dashboard",
  },
  {
    icon: "upcommingJatra",
    label: "Up comming",
    href: navroutes.UPCOMMING_JATRA,
    title: "up-comming",
  },
];

export const jatrasData = [
  {
    id: 1,
    name: "Bisket Jatra",
    location: "Bhaktapur",
    date: "April 14-22, 2024",
    status: "upcoming",
    description:
      "New Year celebration with chariot processions and traditional rituals",
    image: "/bisket-jatra-festival-nepal-chariot-procession.png",
    duration: "9 days",
    popularity: 4.8,
    category: "Religious",
    region: "Kathmandu Valley",
  },
  {
    id: 2,
    name: "Indra Jatra",
    location: "Kathmandu",
    date: "September 17-25, 2024",
    status: "upcoming",
    description:
      "Festival honoring Lord Indra with masked dances and cultural performances",
    image: "/indra-jatra-festival-nepal-masked-dancers.png",
    duration: "8 days",
    popularity: 4.7,
    category: "Cultural",
    region: "Kathmandu Valley",
  },
  {
    id: 3,
    name: "Gai Jatra",
    location: "Kathmandu Valley",
    date: "August 30, 2024",
    status: "upcoming",
    description:
      "Festival of cows with colorful parades and satirical performances",
    image: "/gai-jatra-festival-nepal-cow-parade.png",
    duration: "1 day",
    popularity: 4.6,
    category: "Cultural",
    region: "Kathmandu Valley",
  },
  {
    id: 4,
    name: "Dashain",
    location: "Nationwide",
    date: "October 15-24, 2024",
    status: "upcoming",
    description:
      "Nepal's biggest festival celebrating the victory of good over evil",
    image: "/dashain-festival-nepal-celebration.png",
    duration: "10 days",
    popularity: 4.9,
    category: "Religious",
    region: "All Regions",
  },
  {
    id: 5,
    name: "Tihar",
    location: "Nationwide",
    date: "November 1-5, 2024",
    status: "upcoming",
    description:
      "Festival of lights honoring different animals and relationships",
    image: "/tihar-festival-nepal-lights.png",
    duration: "5 days",
    popularity: 4.8,
    category: "Religious",
    region: "All Regions",
  },
  {
    id: 6,
    name: "Holi",
    location: "Nationwide",
    date: "March 13, 2024",
    status: "completed",
    description: "Festival of colors celebrating spring and love",
    image: "/holi-festival-nepal-colors.png",
    duration: "1 day",
    popularity: 4.7,
    category: "Cultural",
    region: "All Regions",
  },
  {
    id: 7,
    name: "Teej",
    location: "Nationwide",
    date: "August 18, 2024",
    status: "completed",
    description: "Women's festival celebrating marital bliss and well-being",
    image: "/teej-festival-nepal-women-celebration.png",
    duration: "3 days",
    popularity: 4.5,
    category: "Religious",
    region: "All Regions",
  },
  {
    id: 8,
    name: "Janai Purnima",
    location: "Nationwide",
    date: "August 19, 2024",
    status: "completed",
    description: "Sacred thread festival with religious significance",
    image: "/janai-purnima-festival-nepal-sacred-thread.png",
    duration: "1 day",
    popularity: 4.4,
    category: "Religious",
    region: "All Regions",
  },
];
